import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Hero from "../Component/Hero.js";
import Transform from "../Component/Transform";
import Stand from "../Component/Stand";
import GraphPhoto from "../Component/GraphPhoto";
import Testimony from "../Component/Testimony";
import Photogrid from "../Component/Photogrid";
import Footer from "../Component/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Transform />
        <Stand />
        <GraphPhoto />
        <Testimony />
        <Photogrid />
        <Footer />
      </main>
    </div>
  );
}
